# This is an example MERN stack that can be deployed on Porter.
# Run 'porter compose' to deploy.
version: '3'
services:
  porter-mern-backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    image: porter-mern-backend
    container_name: porter-mern-backend
    volumes:
      - ./backend:/src/app
      - /src/app/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - NODE_ENV=development
  mongo:
    image: mongo
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"
  porter-mern-frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    image: porter-mern-frontend
    container_name: porter-mern-frontend
    volumes:
      - ./frontend/:/src/app
      - /src/app/node_modules
    depends_on:
      - porter-mern-backend
    ports:
      - "3000:3000"

volumes:
    data-volume:
    node_modules: